repository: version_suffix doesn't exist, so don't check it
  File "/mnt/media/code/Urcheon/Urcheon/Repository.py", line 391, in getPakFile
    elif version_suffix:
         ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'version_suffix' where it is not associated with a value

Fixes this runtime error